//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T11A
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_LATAM_Entities : DbContext
    {
        public BD_LATAM_Entities()
            : base("name=BD_LATAM_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsientoAvion> AsientoAvion { get; set; }
        public virtual DbSet<Avion> Avion { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Pasaje> Pasaje { get; set; }
        public virtual DbSet<Pasajero> Pasajero { get; set; }
        public virtual DbSet<Tarifa> Tarifa { get; set; }
        public virtual DbSet<TipoServicio> TipoServicio { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<Vuelo> Vuelo { get; set; }
    
        public virtual int SPLATAM_DEL_VENDEDOR(Nullable<int> iIdVendedor)
        {
            var iIdVendedorParameter = iIdVendedor.HasValue ?
                new ObjectParameter("iIdVendedor", iIdVendedor) :
                new ObjectParameter("iIdVendedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPLATAM_DEL_VENDEDOR", iIdVendedorParameter);
        }
    
        public virtual int SPLATAM_INS_VENDEDOR(string iNombres, string iApellidoPaterno, string iApellidoMaterno, string iDni, Nullable<decimal> iSalario, Nullable<bool> iActivo, ObjectParameter oIdVendedor)
        {
            var iNombresParameter = iNombres != null ?
                new ObjectParameter("iNombres", iNombres) :
                new ObjectParameter("iNombres", typeof(string));
    
            var iApellidoPaternoParameter = iApellidoPaterno != null ?
                new ObjectParameter("iApellidoPaterno", iApellidoPaterno) :
                new ObjectParameter("iApellidoPaterno", typeof(string));
    
            var iApellidoMaternoParameter = iApellidoMaterno != null ?
                new ObjectParameter("iApellidoMaterno", iApellidoMaterno) :
                new ObjectParameter("iApellidoMaterno", typeof(string));
    
            var iDniParameter = iDni != null ?
                new ObjectParameter("iDni", iDni) :
                new ObjectParameter("iDni", typeof(string));
    
            var iSalarioParameter = iSalario.HasValue ?
                new ObjectParameter("iSalario", iSalario) :
                new ObjectParameter("iSalario", typeof(decimal));
    
            var iActivoParameter = iActivo.HasValue ?
                new ObjectParameter("iActivo", iActivo) :
                new ObjectParameter("iActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPLATAM_INS_VENDEDOR", iNombresParameter, iApellidoPaternoParameter, iApellidoMaternoParameter, iDniParameter, iSalarioParameter, iActivoParameter, oIdVendedor);
        }
    
        public virtual ObjectResult<SPLATAM_SEL_VENDEDOR_Result> SPLATAM_SEL_VENDEDOR(Nullable<int> iVendedorId, string iNombre)
        {
            var iVendedorIdParameter = iVendedorId.HasValue ?
                new ObjectParameter("iVendedorId", iVendedorId) :
                new ObjectParameter("iVendedorId", typeof(int));
    
            var iNombreParameter = iNombre != null ?
                new ObjectParameter("iNombre", iNombre) :
                new ObjectParameter("iNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPLATAM_SEL_VENDEDOR_Result>("SPLATAM_SEL_VENDEDOR", iVendedorIdParameter, iNombreParameter);
        }
    
        public virtual int SPLATAM_UPD_VENDEDOR(Nullable<int> iIdVendedor, string iNombres, string iApellidoPaterno, string iApellidoMaterno, string iDni, Nullable<decimal> iSalario, Nullable<bool> iActivo)
        {
            var iIdVendedorParameter = iIdVendedor.HasValue ?
                new ObjectParameter("iIdVendedor", iIdVendedor) :
                new ObjectParameter("iIdVendedor", typeof(int));
    
            var iNombresParameter = iNombres != null ?
                new ObjectParameter("iNombres", iNombres) :
                new ObjectParameter("iNombres", typeof(string));
    
            var iApellidoPaternoParameter = iApellidoPaterno != null ?
                new ObjectParameter("iApellidoPaterno", iApellidoPaterno) :
                new ObjectParameter("iApellidoPaterno", typeof(string));
    
            var iApellidoMaternoParameter = iApellidoMaterno != null ?
                new ObjectParameter("iApellidoMaterno", iApellidoMaterno) :
                new ObjectParameter("iApellidoMaterno", typeof(string));
    
            var iDniParameter = iDni != null ?
                new ObjectParameter("iDni", iDni) :
                new ObjectParameter("iDni", typeof(string));
    
            var iSalarioParameter = iSalario.HasValue ?
                new ObjectParameter("iSalario", iSalario) :
                new ObjectParameter("iSalario", typeof(decimal));
    
            var iActivoParameter = iActivo.HasValue ?
                new ObjectParameter("iActivo", iActivo) :
                new ObjectParameter("iActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPLATAM_UPD_VENDEDOR", iIdVendedorParameter, iNombresParameter, iApellidoPaternoParameter, iApellidoMaternoParameter, iDniParameter, iSalarioParameter, iActivoParameter);
        }
    }
}
